default_language_version:
  node: system

repos:
  # eslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.10.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(js|jsx|ts|tsx)$
        args: [--report-unused-disable-directives]
        additional_dependencies:
          # Use the same versions as the project’s package-lock.json.
          - '@typescript-eslint/eslint-plugin@5.60.0'
          - '@typescript-eslint/parser@5.60.0'
          - eslint@8.43.0
          - eslint-config-prettier@8.8.0
          - eslint-plugin-react@7.32.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.1
          - typescript@5.0.4

  # prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
